feat: add custom link
koreanbots/link pull request #4
Opened 2022-05-28 02:38 UTC by chul0721

2022-05-29 09:06 UTC, wonderlandpark requested changes
내부 채팅으로 리뷰 사항을 전달해드렸습니다 :)

2022-05-29 09:06 UTC, wonderlandpark commented on .env.example
> +PORT=4000
변경하신 특별한 이유가 있을까요??

2022-05-29 09:18 UTC, chul0721 commented on .env.example
> +PORT=4000
시크릿 키 넣다가 포트를 지워서 다시 작성하다가 이렇게 된것 같네요 ㅋㅋ

2022-10-08 13:52 UTC, eunwoo1104 approved these changes

2022-10-08 13:55 UTC, eunwoo1104 commented
@wonderlandpark 일단 우선 테스트 서비스 먼저 시작하는게 맞을 것 같아서 제가 리뷰하고 머지했어요! 혹시라도 이후에 리뷰 사항 있으시면 디스코드로 알려주시면 될 것 같아요.

2022-10-08 13:56 UTC, merged